landingpage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "landingpage"

urlpatterns = [
    path('', views.add_status, name="add"),
]

story10/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "story10"

urlpatterns = [
    path('', views.story10_home, name="home"),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('story10/', include('story10.urls')),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "story7"

urlpatterns = [
    path('', views.profile_views , name = "profile_views"),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "story8"

urlpatterns = [
    path('', views.find_books, name="find_books"), 
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "story9"

urlpatterns = [
    path('', views.home_view, name="home"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout") 
]

landingpage/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
    title = models.CharField(max_length=300)
    date_and_time = models.DateTimeField(auto_now_add = True)

story10/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

landingpage/forms.py
from django import forms
from .models import Status

class AddStatusForm(forms.ModelForm):
    title = forms.CharField(
        widget = forms.Textarea(
            attrs = {
                'class':'form-body',
                'placeholder' : "Enter a new status",
                'required' : True,
                'id' :'id-title',
            }
        )
    )
    class Meta:
        model = Status
        fields = [
            'title',
        ]

landingpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Status
from .forms import AddStatusForm

def add_status(request):
    form = AddStatusForm()
    list_status = Status.objects.all().order_by('date_and_time')
    if request.method == "POST":
        form = AddStatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, "landingpage/home.html", {"form":form, "list_status":list_status})

story10/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse

def story10_home(request):
    response = {'port':request.META['SERVER_PORT']}
    return render(request, "story10/story10.html", response)

story7/views.py
from django.shortcuts import render
from django.http import HttpResponse

def profile_views(request):
    return render(request, "story7/story7-home.html")

story8/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse

def find_books(request):
    return render(request, "story8/find_books.html")

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

def home_view(request):
    user = request.user
    if user.is_authenticated:
        return render(request, "story9/home.html")
    else:
        return redirect("story9:login")

def login_view(request):
    user = request.user
    login_form = AuthenticationForm()

    if user.is_authenticated:
        return render(request,'story9/home.html')
    if request.method == "POST":
        login_form = AuthenticationForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect("story9:home")
    return render(request,'story9/login_view.html', {'form':login_form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
    return redirect('story9:login')

landingpage/templates/landingpage/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Add Status</title>
</head>
<body>
    <div class="container column-style" id="add-status">
        <h1>Halo, apa kabar?</h1>
        <div class="container column-style form-style">
            <form action="" class="form-container" name="add-status-form" method="POST">
                {% csrf_token %}
                <div class="container column-style form-style">
                    <span class="title" id="judul1">Input status kamu</span>
                    {{ form.title }}
                    <input type="submit" id='submit' class="btn" value="Submit">
                </div>
            </form>
        </div>
        <div class="container column-style" id="list-items">
            <div class="container max-width">
                <span class="title">Daftar Status Kamu</span>
            </div>
            {% for item in list_status %}
                <div class="container column-style items">
                    <span class="subtitle">{{ item.title }}</span>
                    <span class="body-txt">{{ item.date_and_time }}</span>
                </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

story10/templates/story10/story10.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Story 10</title>
</head>
<body>
    <div class="container column-style">
        <span class="title">Test Story 10</span>
        {{ port }}
    </div>
</body>
</html>

story7/templates/story7/story7-home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="{% static 'js/story7.js' %}"></script>
    <title>Story 7</title>
</head>
<body>
    <div class="container column-style" id="story7-home">
        <div class="container right">
            <button class="btn" onclick="gantiWarna()">Change Background</button>
        </div>
        <span class="title" id="judul">Hello people!</span>
        <div class="container row-style" id="profile">
            <div class="" id="about-left">
                <img src="{% static 'img/foto.png' %}" alt="profile image" id="profile-img">
            </div>
            <div class="container column-style" id= "about-right">
                <span class="subtitle">
                    My name is Christopher Yohanes Hasian Tamba and you can call me 
                    Christo.
                </span>
                <span class="subtitle">
                    I'm currently an 
                    <span class="bold-txt">Information System</span>
                    student at 
                    <span class="bold-txt">University of Indonesia</span>.
                </span>
                <span class="subtitle">
                    I love to study technology
                    and how it works to make a great impact in business.
                </span>
            </div>
        </div>
        <div class="container column-style left max" id="accordion">
            <span class="title acc-title">My Activities</span>
            <div class="container column-style left max acc-items">
                <span class="subtitle">- Learn, Study, and Exercise</span>
                <span class="subtitle">- Playing musical instruments</span>
                <span class="subtitle">- Watching Youtube</span>
            </div>
            <span class="title acc-title">My Experiences</span>
            <div class="container column-style left max acc-items">
                <span class="subtitle">- Staff of Business IT Competition, Compfest 11</span>
                <span class="subtitle">- Staff of Mentor and Student Division, BETIS 2019</span>
            </div>
            <span class="title acc-title">My Achievements</span>
            <div class="container column-style left max acc-items">
                <span class="subtitle">- Entering University of Indonesia</span>
                <span class="subtitle">- Best Graduate of SMAN 91 Jakarta (2018)</span>
            </div>        
        </div>
    </div>
</body>
</html>

story8/templates/story8/find_books.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Find Books</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/story8.js' %}"></script>
</head>
<body>
    <div class="big-box" id="story8-home">
        <div class="container column-style">
            <span class="title">
                <b>Search Your Favorite Books!</b>
            </span>
        </div>
        <div class="container row-style" id="inputan-story8">
            <input type="text" id="search" placeholder="Search books">
            <input type="submit" class="btn" id="btn-search" value="search">
        </div>
        <div class="container max-width" id="">
            <table id="results">
                <tr> 

                </tr>
            </table>
        </div>
    </div>
    
</body>
</html>

story9/templates/story9/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Hello!!</title>
</head>
<body>
    <div class="big-box">
        <div class="container column-style" id="story9-home">
            <span class="title story9-items">Hello {{ user.username }}!</span>
            <span class="subtitle story9-items">
                Selamat datang di fitur login yang kamu buat sendiri.
                Senang ya akhirnya fitur login kamu berhasil. Semangat terus
                menjalani kehidupan ini. Semoga IP semester 3 ini bisa tembus 4.00.
            </span>
            <form action="{% url 'story9:logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">
                    Logout
                </button>

            </form>
        </div>
    </div>
</body>
</html>

story9/templates/story9/login_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Login</title>
</head>
<body>
    <div class="bigbox">
        <div class="container column-style" id="story9-login">
            <span class="title story9-items" >Silakan Login</span>
            <form action="{% url 'story9:login' %}" method="POST" id="login-form">
                {% csrf_token %}
                <div class="row-style story9-items">
                    <span class="subtitle">Username</span>
                    {{ form.username }}
                </div>
                <div class="row-style story9-items">
                    <span class="subtitle">Password</span>
                    {{ form.password }}
                </div>
                <div class="container">
                    <button type="submit" class="btn">Login</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>